// src/components/theme-toggle/theme-toggle.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { ThemeService } from '../../services/theme.service';

@Component({
  selector: 'app-theme-toggle',
  templateUrl: './theme-toggle.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ThemeToggleComponent {
  constructor(public themeService: ThemeService) {}

  toggleTheme = () => {
    this.themeService.toggleTheme();
  }
}
<button (click)="toggleTheme()" class="text-2xl w-10 h-10 flex items-center justify-center rounded-full hover:bg-black/10 dark:hover:bg-white/10 transition-colors">
  @if (themeService.theme() === 'light') {
    <span>🤍</span>
  } @else {
    <span>💗</span>
  }
</button>

// src/components/ThemeToggle.jsx
import { useTheme } from '../context/ThemeContext';

const ThemeToggle = () => {
  const { theme, toggleTheme } = useTheme();

  return (
    <button
      onClick={toggleTheme}
      className="text-2xl w-10 h-10 flex items-center justify-center rounded-full hover:bg-black/10 dark:hover:bg-white/10 transition-colors"
      aria-label="Toggle theme"
    >
      {theme === 'light' ? '🤍' : '💗'}
    </button>
  );
};

export default ThemeToggle;
